dubbo:
    scan:
        base-packages: com.tsco.member.dubboService
    application:
        name: member
    protocol:
        name: dubbo
        port: 20881
    registry:
        address: zookeeper://127.0.0.1:2181
        check: true
logging:
  config: classpath:logback/logback-dev.xml
