dubbo:
    scan:
        base-packages: com.tsco.member.dubboService
    application:
        name: member
    protocol:
        name: dubbo
        port: 20881
    registry:
        address: zookeeper://101.132.143.173:2181
        check: true