CREATE TABLE SUBJECT(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  TYPE VARCHAR(50) COMMENT '题目类型',
  TITLE VARCHAR(255) COMMENT '标题',
  CONTENT VARCHAR(255) COMMENT '题目内容',
  CREATED_BY BIGINT UNIQUE COMMENT '题目创建人',
  ANSWER VARCHAR(255) COMMENT '题目答案',
  STATUS VARCHAR(50) COMMENT '题目状态',
  CREATED_AT TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  UPDATED_AT TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  FOREIGN KEY (CREATED_BY) REFERENCES USER(ID)
)ENGINE =InnoDB;

CREATE TABLE ANSWER_RECORD(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  USER_ID BIGINT NOT NULL COMMENT '用户id',
  SUBJECT_ID BIGINT NOT NULL COMMENT '题号',
  RESULT VARCHAR(50) COMMENT '结果',
  CREATED_AT TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  UPDATED_AT TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID)
)ENGINE =InnoDB;

CREATE TABLE ACTION_RECORD(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  USER_ID BIGINT NOT NULL COMMENT '用户ID',
  EVENT VARCHAR(50) COMMENT '操作事件',
  REMARK VARCHAR(255) COMMENT '备注',
  IP VARCHAR(50) COMMENT 'IP',
  CREATED_AT TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
)ENGINE =InnoDB;















