dubbo:
    scan:
        base-packages: com.tsco.common.dubboService
    application:
        name: common
    protocol:
        name: dubbo
        port: 20882
    registry:
        address: zookeeper://127.0.0.1:2181
        check: true