dubbo:
    scan:
        base-packages: com.tsco.common.dubboService
    application:
        name: common
    protocol:
        name: dubbo
        port: 20883
    registry:
        address: zookeeper://101.132.143.173:2181
        check: true