CREATE TABLE USER (
  ID         BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  USER_NAME  VARCHAR(50) COMMENT '用户名',
  EMAIL      VARCHAR(50) NOT NULL COMMENT '邮箱',
  PASSWORD   VARCHAR(50) NOT NULL COMMENT '密码',
  GENDER     VARCHAR(5)  DEFAULT 'MALE' COMMENT '性别',
  BIRTHDAY   DATE        COMMENT '生日',
  ADDRESS    VARCHAR(50) COMMENT '地址',
  USER_ROLE  VARCHAR(10) NOT NULL DEFAULT 'MEMBER' COMMENT '用户类型',
  CREATED_AT TIMESTAMP   NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATED_AT TIMESTAMP   NOT NULL DEFAULT NOW() COMMENT '更新时间'
)ENGINE =InnoDB;