CREATE TABLE USER (
  ID         BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  USERNAME   VARCHAR(50) NOT NULL COMMENT '用户名',
  EMAIL      VARCHAR(50) NOT NULL COMMENT '邮箱',
  PASSWORD   VARCHAR(50) NOT NULL COMMENT '密码',
  SEX        VARCHAR(2)  NOT NULL COMMENT '性别',
  BIRTHDAY   DATE        NOT NULL COMMENT '生日',
  ADDRESS    VARCHAR(50) COMMENT '地址',
  USERTYPE   VARCHAR(10) NOT NULL DEFAULT 'MALE' COMMENT '用户类型',
  CREATED_AT TIMESTAMP   NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATED_AT TIMESTAMP   NOT NULL DEFAULT NOW() COMMENT '更新时间'
)ENGINE =InnoDB;